### ISSUE TITLE
Can't get it to work on files bigger than 20MB

### ISSUE THREAD

**Issue by Rick7C2** [J05HI/google-drive-direct-remote-upload#1]
I tried using this with the ddownload links from..
https://www.thinkbroadband.com/download

I can only get it to work with 5MB, 10MB, & 20MB.

Everything else finishes without error but the file does not appear in my gdrive.

Any ideas?

Also what would I need to change to make it work on a website?

**Comment by J05HI** [comment]
@Rick7C2
Uploading files should work with any filesize.
Could you please describe your problem better :)

**Comment by spookyahell** [comment]
I have the same issue, but only for thinkbroadband.com... I wonder why this is... maybe Google rejecting the data?  `An error occurred: Upload failed` happens every time I've tried to upload a file bigger than 100 MB... (100 MB from NON-thinkbroadband site)

**Comment by J05HI** [comment]
Strange

**Comment by J05HI** [comment]
Let's see what I can do
