### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [J05HI/google-drive-direct-remote-upload#11]
.

**Comment by J05HI** [comment]
What do you mean?
Downloads aren't supported. It's for uploading files remotely to Google Drive.

**Comment by Toni195** [comment]
This is what I'm talking about.
https://git.teknik.io/SMLoadrDev/SMLoadr/releases

**Comment by J05HI** [comment]
I'm not the maintainer anymore
I was long time ago
Ask in their Telegram group for help
