### ISSUE TITLE
hi , may i know this php still work ?

### ISSUE THREAD

**Issue by bhoeyong** [J05HI/google-drive-direct-remote-upload#14]
hi , may i know this php still work ? i always get error

This application must be run on the command line. You need to modify it a bit to run over the browser :)Open the following link in your browser: https://accounts.google.com/o/oauth2/auth?response_type=code&access_type=offline&client_id=87546652136-hd50li2njm2909ik09oj0nodl0f77s58.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fh-ds.herokuapp.com%2Findex.php&state&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&approval_prompt=force Enter verification code: An error occurred: Invalid code

**Comment by J05HI** [comment]
@bhoeyong
Hey, did you execute it from the command line?

**Comment by bhoeyong** [comment]
hi bro..means wan to delete this line ?

if ('cli' !== PHP_SAPI) {
    echo('This application must be run on the command line. You need to modify it a bit to run over the browser :)');
}

**Comment by bhoeyong** [comment]
this i edit it

{
    "web": {
        "client_id":                   "87546652136-hd50li2njm2909ik09oj0nodl0f77s58.apps.googleusercontent.com",
        "project_id":                  "theta-gizmo-249504",
        "auth_uri":                    "https://accounts.google.com/o/oauth2/auth",
        "token_uri":                   "https://accounts.google.com/o/oauth2/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_secret":               "B_aHKBoS1LMqcCIFY8Okn2LA",
        "redirect_uris":               [
            "https://h-ds.herokuapp.com/index.php"
        ],
        "javascript_origins":          [
            "http://localhost"
        ]
    }
}

**Comment by J05HI** [comment]
Hey, this project is not meant to be used from the browser. You have to execute it from the command line.
You can modify the code to fit your needs.

**Comment by J05HI** [comment]
@bhoeyong
Hey, this project is not meant to be used from the browser. You have to execute it from the command line.
Otherwise you can modify the code to fit your needs.
