### ISSUE TITLE
gphotos

### ISSUE THREAD

**Issue by Abdel-ilah** [J05HI/google-drive-direct-remote-upload#2]
Thank you
can we do the same thing for google photo?

**Comment by J05HI** [comment]
@Abdel-ilah
You mean multiple pictures upload?

**Comment by Abdel-ilah** [comment]
remote upload files to gphotos from url

**Comment by J05HI** [comment]
@Abdel-ilah

You should do this over the Picasa Web Albums Data API. 
[https://developers.google.com/picasa-web/](https://developers.google.com/picasa-web/)
