### ISSUE TITLE
composer lock

### ISSUE THREAD

**Issue by nk932714** [J05HI/google-drive-direct-remote-upload#3]
please add a composer lock file to deploy it on heroku

**Comment by J05HI** [comment]
Okay thanks!

**Comment by nk932714** [comment]
welcome buddy ! waiting for composer lock so that i can use this repo on heroku. Without composer lock i am unable to deploy it on heroku showing error.

**Comment by J05HI** [comment]
@nk932714
Sorry I've forgotten it
Will do it this evening

**Comment by J05HI** [comment]
@nk932714 
Done :)

**Comment by nk932714** [comment]
thanks a lot buddy :)
