### ISSUE TITLE
Heroku issue

### ISSUE THREAD

**Issue by nk932714** [J05HI/google-drive-direct-remote-upload#4]
HI can you please test this repo on heroku if you have time,

i have deployed it on heroku and opened it, a blank page is showing & nothing else,

**Comment by J05HI** [comment]
Don't know
It's only an example.
How you integrate this in your projects is your thing.

**Comment by J05HI** [comment]
Test it with PHP console on your machine.

**Comment by nk932714** [comment]
i just deployed it on heroku , heroku automatically detect the php platform, but whenever i am opening the deployed code blank page is showing i think i shoud try this code on other hosting site( heroku is a free platform also downloading and uploading speed is also good.)

**Comment by Afa1482** [comment]
@nk932714
Hi, did you manage to get it to work on heruko?
