### ISSUE TITLE
smloadr

### ISSUE THREAD

**Issue by jackpot08** [J05HI/google-drive-direct-remote-upload#5]
how can i follow development on smloafdr

**Comment by J05HI** [comment]
@jackpot08 

Deezer took it down :(
So I'm out of this... 
Anyway here the Telegram group: [https://t.me/SMLoadrNews](https://t.me/SMLoadrNews)

**Comment by dOooOb** [comment]
https://github.com/svbnet/Athame/issues/59#issuecomment-359107482
https://github.com/svbnet/Athame/issues/59#issuecomment-359108286
