### ISSUE TITLE
Can't make this work

### ISSUE THREAD

**Issue by putuoka** [J05HI/google-drive-direct-remote-upload#7]
i run it from cmd on windows
and follow what it say to verification credential via browser
but this is what i got https://i.imgur.com/OCI5Qw3.png

**Comment by J05HI** [comment]
@putuoka
Could you please re-upload it.
I can't read it because it's too blurry

**Comment by putuoka** [comment]
Hmm.. strange my image dimension on imgur is 1505x450 that's large and should be read able. it seem imgur site has problem.
please try with this link man https://dsds-jtommasope692890.codeanyapp.com/image2.png

the callback redirect to my localhost in your project root index.php which is not allow opening in web and also doesn't have $_GET['code'] to capture callback code from api. not sure what should do.
Thanks for helping

**Comment by J05HI** [comment]
@putuoka
Strange...
You registered localhost on the Google Cloud Console?

**Comment by putuoka** [comment]
No. I'm not setting up any url to my google developer console. i just created oauth client to take secret key and used it on this app. I think the problem is your index.php doesn't have $_GET['Code'] to capture auth call back. Because after the step "open the following link in your browser" when open the link in browser google authenticate the key and after that redirect the callback to this address index.php?code=blabla while your index.php root doesn't have $_GET['code'] also doesn't allow browser access just in cli/console. I'll make the video later to explain what is missing from my step installation. I'm very exited with this project.

**Comment by J05HI** [comment]
@putuoka
Okay I'll take a look at it if I've time
