### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by bsde1245** [J05HI/google-drive-direct-remote-upload#8]
When issue php index.php I get

```
require_once(/home/justinechacko/Web/google-drive-direct-remote-upload/vendor/autoload.php): failed to open stream: No such file or directory in /home/justinechacko/Web/google-drive-direct-remote-upload/index.php on line 9
PHP Fatal error:  require_once(): Failed opening required '/home/justinechacko/Web/google-drive-direct-remote-upload/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/justinechacko/Web/google-drive-direct-remote-upload/index.php on line 9
```

**Comment by J05HI** [comment]
Looks like you haven't run "composer install"
Sorry, I forgot to add it to the Readme

**Comment by bsde1245** [comment]
Ok, also what is the javascript_origin if I host it on heroku

**Comment by J05HI** [comment]
Address of the server

**Comment by soumjoyel** [comment]
It is asking for verification code

`https://accounts.google.com/o/oauth2/auth?response_type=code&access_type=offline&client_id=19656302577-bak33lo76i68o2n7u2e4pb48mbtep88l.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsavetogdrive.herokuapp.com%2Findex.php&state&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&approval_prompt=force`

**Comment by bsde1245** [comment]
It is asking for verification code

`https://accounts.google.com/o/oauth2/auth?response_type=code&access_type=offline&client_id=19656302577-bak33lo76i68o2n7u2e4pb48mbtp88l.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Flocalhost%2Findex.php&state&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&approval_prompt=force`

I get following error: localhost cannot be reached?
I cant access local host. I installed php only? Do I need to install apache?

**Comment by bsde1245** [comment]
Okey, it displays index.php in the following link `http://localhost/google-drive-direct-remote-upload/index.php?code=4/AABMbyixu2LOI2s36r1iyc0-PVoYkrWwjn6Y3dkpJ7kTI9vvulJQYSRuxxE4q3MGmodEuWP5GN5q49akWhW7RI#`

Where can I find verification code?

**Comment by J05HI** [comment]
I don't know it that well anymore but I think it's:
AABMbyixu2LOI2s36r1iyc0-PVoYkrWwjn6Y3dkpJ7kTI9vvulJQYSRuxxE4q3MGmodEuWP5GN5q49akWhW7RI
