### ISSUE TITLE
I got it to work, BUT... xD

### ISSUE THREAD

**Issue by spookyahell** [J05HI/google-drive-direct-remote-upload#9]
I unterstand you worked on it a while back but I figured out ONE thing that is funny about this script!
It's currently useless... it uploads a file "Test File.zip" from thinkbroadband.com to my Google Drive.
So test mode is activated. All you need to do is make it so one can enter a URL into the script somehow...

If you change the url 20 MB file can be uploaded, 100 MB test file from [Hetzner](https://speed.hetzner.de/) can also be downloaded. I tried some other file links but those didn't work. I will get back if something changes or if I find out sth else...

But: Very nice demo script! Love it.

**Comment by J05HI** [comment]
Yeah that's true
It was a little test. Took me some time to figure out how it works. That's why I shared it here.
If you like you can create a pull request :)

**Comment by J05HI** [comment]
Should be fixed now with the latest commit
